TIME_STEP = 32

# Motion Parameters
MAX_SPEED = 4.5
DANGER_DEPTH = 0.7

# Safe thresholds for Webots Pioneer Sonar arrays
SAFE_PROXIMITY_LIMIT = 0.18
OBSTACLE_DETECTION_THRESHOLD = 0.9
SIDE_DETECTION_THRESHOLD = 0.4
PIVOT_CLEARANCE_THRESHOLD = 0.7
HIT_CONTACT_THRESHOLD = 0.30
HIT_RECOVERY_COOLDOWN = 40
CONTACT_RECOVERY_REVERSE_STEPS = 15
CONTACT_RECOVERY_TURN_STEPS = 30
REPEATED_COLLISION_FLIP_THRESHOLD = 2
SECONDARY_AVOIDANCE_RECOVERY_STEPS = 20
SECONDARY_AVOIDANCE_COOLDOWN = 40

# Avoid spinning - front clearance needed to proceed
FRONT_CLEARANCE_THRESHOLD = 1.2

# Side Wall Following Distance
TARGET_WALL_DISTANCE = 0.22

# Wall Following Strength
WALL_FOLLOW_GAIN = 1.8

# TARGET DESTINATION COORDINATES (The other side of the road)
# Adjust these coordinates to match the exact opposite end of your world canvas layout
TARGET_GOAL_X = 5.0
TARGET_GOAL_Z = 0.5

# Grid Settings
CELL_SIZE = 1.0
WATER_BLUE_THRESHOLD = 120

# State Machine Nodes
STATE_STARTUP = "STARTUP_CHECK"
STATE_PATROL  = "PATROL_NAV"
STATE_SCAN    = "HAZARD_SCAN"
STATE_AVOID   = "AVOID_RETREAT"
STATE_REPORT  = "REPORT_ZONE"

